### ISSUE TITLE
support Debian?

### ISSUE THREAD

**Issue by UnixJunkie** [eddelbuettel/r2u#1]
Dear Dirk,

Nice project for the hurried R user.

It would be nice to support Debian.
Ubuntu being a Debian derivative, I even wonder if supporting Debian first
would not have given you Ubuntu being supported for free.

Regards,
F.

**Comment by eddelbuettel** [comment]
Sure. I am a Debian developer after all. And the documentation says so (in Section 'What is Covered'):

> Support for other distributions is possible but unlikely right now (due to a lack of resources and time). We hope to cover Debian at some point.

But there are deep technical reasons why it was quicker to start with Ubuntu, and given that I currently do this as a (single) volunteer I will not have the resources to do this.  Which is what I wrote there.  Other volunteer efforts could help, and I made my code public...
