### ISSUE TITLE
Incorrect comment referring to 4.2.0 in add_cranapt_jammy.sh

### ISSUE THREAD

**Issue by davidkane9** [eddelbuettel/r2u#15]
Consider this comment from add_cranapt_jammy.sh:

> Third: ensure R 4.2.0 is used (could use Launchpad source or edd PPA too)

I don't think that the comment is correct. I *think* that the code merely ensures that the latest version of R will be used, not that it will be 4.2.0. For example, when I run the script now I see R 4.2.1.

Apologies if I am missing something! Thanks for a cool tool!

**Comment by eddelbuettel** [comment]
Well spotted!  It _was_ R 4.2.0 when I wrote it (pre-release, basically) but that apt repository essentially ensures _current_ R now, and going forward.  Will adjust.

And lovely to hear from you. Congrats on the new gig, and huge kudos on the high-schooler course which, thanks to the massive megaphone owned by @andrewheiss, I became aware of too.  You makes us adjunct part-timers pale in comparison!

**Comment by davidkane9** [comment]
Lunch is on me next time you are in Boston! By the way, do you have any interest in issue reports from using this on Gradescope, which is a company which provides automatic grading services to lots of universities? It doesn't quite work (only showing the 400 or so packages). No worries if that use case is too fringgy or proprietary to bother with.

**Comment by eddelbuettel** [comment]
Well you know I am over in camp 'U of Illinois' and there is a rather nice (locally developed, but now used at Berkeley, UBC (Vancouver), NYU, York U (Toronto) and what not):  https://www.prairielearn.org/. It's honestly good -- has supported my course for a few years.  Now a scheduler / test runner / ... https://www.prairietest.org/ to go with it.  Wrote up a short piece on the R autograder I set up for it:  https://arxiv.org/abs/2003.06500 (may need an update).  Open source and all (though I guess non-UIUC user pay for the cloud setup -- I am a little in the dark there...)

But yes I am overdue a Boston visit anyway....

**Comment by eddelbuettel** [comment]
Fixed in the README.md (and updated website generated with it) and two scripts.  Thanks again for the heads-up!
