### ISSUE TITLE
How to install specific version of cran package?

### ISSUE THREAD

**Issue by s-eiermann** [eddelbuettel/r2u#31]
I'm using your docker container to run and install packages via: `install.r <libs>`. How can I install specific versions of the R packages?
Thanks

**Comment by eddelbuettel** [comment]
You cannot as R and CRAN do not work that way, and neither does `apt` (well it kinda sorta does but we do not have indices).

So in short the value proposition and offer of r2u is to give you _all_ of CRAN _as it currently is_ fast and reliably.  That is in fact fairly unique, and we do it 'across two dimensions' for the two most recent LTS releases of Ubuntu.  We never claimed we would magically surface a third dimension across time.  That _could_ conceivably be done, but it a lot more work. 

So ok if I close this as 'out of scope'?  I still hope you find r2u of use.

**Comment by s-eiermann** [comment]
Ok, no problem.

The reason I'm asking is, that currently there are two packages which current versions are incompatible with each other....
There's a fix on a master branch - So I'd prob. have to manually override the installation, to fetch that package from GitHub instead? Thanks

**Comment by eddelbuettel** [comment]
Can you detail which packages you are having problems with?  I had a little bit of that at the very beginning but the combination of a) having everything and b) the "`apt` pinning" made it go away completely for all my use cases.

**Comment by s-eiermann** [comment]
The author of `fabletools` has fixed an issue on his master branch, but not yet published to cran...
https://github.com/tidyverts/fabletools/commit/dd9027da9c21d99b9f2c8dbb662d7ae465933e68

**Comment by eddelbuettel** [comment]
Ok, so you need to install that from GitHub. For which `remotes::install_github()` is widely used, and my containers generally have the `installGithub.r` wrapper from `littler`.  That is all you need.

(There is a current, temporary misalignment between what `bspm` thought correct a few weeks ago and what we now think so just for now you may need to prefix it with `bspm::disable()` inside the r2u container.  This should be fixed 'soon'.)
