### ISSUE TITLE
RQuantLib is uninstallable on r2u:jammy

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/r2u#37]
Reported via [toot by Dave Vanness](https://mastodon.social/@djvanness@econtwitter.net/110583664498764247) a few hours ago.

Confirmed on my 23.04 laptop accessing r2u:22.04.

The culprit is the inclusion of my very own PPA which lets the most current QuantLib library seep in _during build time_ but the during run-time we do not have the same library -- boom.  Uninstallable.  QuantLib being complicated adding the PPA to the run-time will likely not help as the underlying binary build is from the LTS release 22.04.  So a better fix is likely to just turn off the PPA use which I shall try next.

**Comment by eddelbuettel** [comment]
This is now taken care of:

```sh
$ docker run --rm -ti rocker/r2u:jammy 
root@[randomstring]:/# Rscript -e 'install.packages("RQuantLib")'
[....lines omitted...]
Setting up r-cran-rquantlib (0.4.18-1.ca2204.2) ...    # note the .2: updated binary
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
root@[randomstring]:/# R
[...]
> library(RQuantLib)
RQuantLib 0.4.18 built with QuantLib version 1.25. See https://www.quantlib.org for more on QuantLib.
> 
```

**Comment by djvanness** [comment]
Amazing - thank you. I don't know how you get all of this done.
