### ISSUE TITLE
vdiffr has graphics API version mismatch with current R

### ISSUE THREAD

**Issue by jranke** [eddelbuettel/r2u#42]
Not sure if I analysed the situation correctly, but it seems that r-cran-vdiffr in r2u for jammy needs a rebuild, as it fails to work with R 4.3.1:

https://app.travis-ci.com/github/jranke/mkin/builds/265560310

You can see that R 4.3.1-4 is installed on line 695:

https://app.travis-ci.com/github/jranke/mkin/builds/265560310#L695

and the following lines illustrate (I think) that vdiffr comes from r2u:

https://app.travis-ci.com/github/jranke/mkin/builds/265560310#L1711
https://app.travis-ci.com/github/jranke/mkin/builds/265560310#L1793

I am a bit confused, because in the log, the package is retrieved after it has been set up. Presumably just a matter of output buffering.

Am I correct to assume that a rebuild of vdiffr in r2u would fix this?

Thankful for all of these amazing tools, as always,

Johannes

**Comment by eddelbuettel** [comment]
Flim!  I caught a good handful of these when R 4.3.1 came out and caused 'Graphics API version mismatch' for binaries produced under R 4.2.*.  I will make sure I rebuild `vdiffr` too in today's update.  I mentioned to Kurt that the communication from R Core about these graphics API changes (for three R releases in a row) is not ideal.  Oh well.

Thanks for the heads-up, will fix later today.

**Comment by eddelbuettel** [comment]
"Well actually" that package was just rebuilt yesterday (and it hence a fresh bug). Strange. Anyway, I will force a rebuild.

**Comment by eddelbuettel** [comment]
We should be good now:

```sh
[....]
Setting up r-cran-vdiffr (1.0.6-1.ca2204.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
root@[...]:/# R

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> vdiffr:::svglite("/tmp/foo")
> 
```

**Comment by jranke** [comment]
Thanks a lot for your quick action, much appreciated - I confirm it works on Travis, too!
