### ISSUE TITLE
Are certain Bioconductor packages out of date?

### ISSUE THREAD

**Issue by rcannood** [eddelbuettel/r2u#44]
I've been getting some issues with using bioconductor packages related to images that should have already been solved in Bioconductor 3.17.

Looking at https://r2u.stat.illinois.edu/ubuntu/pool/dists/jammy/main/ it seems (for example) that DelayedArray was last updated on June 12th when it was updated to v0.26.3-1:

    r-bioc-csaw_1.34.0-1.ca2004.2_amd64.deb            28-Apr-2023 05:30             1116136
    r-bioc-decipher_2.28.0-1.ca2004.2_amd64.deb        28-Apr-2023 05:19            16072628
    r-bioc-delayedarray_0.26.3-1.ca2004.1_amd64.deb    12-Jun-2023 15:25             1931432 <--
    r-bioc-delayedmatrixstats_1.22.0-1.ca2004.2_all..> 28-Apr-2023 04:38              672268
    r-bioc-deseq2_1.40.2-1.ca2004.1_amd64.deb          14-Jul-2023 19:57             2578212
    r-bioc-diffbind_3.10.0-1.ca2004.2_amd64.deb        28-Apr-2023 13:05             7175872

However, the latest release of DelayedArray on Bioconductor 3.17 is 0.26.7 ([link](https://bioconductor.org/packages/release/bioc/html/DelayedArray.html)). This is also the version available in the posit package manager ([link](https://packagemanager.posit.co/client/#/repos/4/packages/DelayedArray)). 

The only solution I found for now is installing DelayedArray from source, which misses the entire point of r2u.

Could it be that _something_ is wrong with the procedure for updating the r2u apt repository, or is this intended behaviour?

Thank you for taking the time to look into this issue.

**Comment by eddelbuettel** [comment]
Could be -- help welcome!   Could you cook up and run `available.packages()` and compare?

"By design" we run against CRAN and pull in BioC as needed.  That leaves the door open for something to be stale.

**Comment by eddelbuettel** [comment]
I think I have a handle on it.  It is simply not an update run I have done, but should do. Maybe weekend-ish. Current subset among those already built:

```r
> ap[newpkgs,.(Package, Version),on="pkgver"]
               Package Version
                <char>  <char>
 1:               affy  1.78.2
 2:    AnnotationForge  1.42.2
 3:             apeglm  1.22.1
 4:             CelliD   1.8.1
 5:           cliqueMS  1.14.1
 6:    clusterProfiler   4.8.3
 7:       DelayedArray  0.26.7
 8: DelayedMatrixStats  1.22.6
 9:           DiffBind  3.10.1
10:               DOSE  3.26.1
11:             gdsfmt  1.36.1
12:         genefilter  1.82.1
13:        GeneticsPed  1.62.1
14:       GenomeInfoDb  1.36.2
15:    GenomicFeatures  1.52.2
16:             ggtree   3.8.2
17:       GreyListChIP  1.32.1
18:               Gviz  1.44.1
19:          HDF5Array  1.28.1
20:              HIBAG  1.36.2
21:         HiCcompare  1.22.1
22:     InteractionSet  1.28.1
23:             lefser  1.10.1
24:                lfa  2.0.11
25:     MatrixGenerics  1.12.3
26:    multiHiCcompare  1.18.1
27:                mzR  2.34.1
28:            qpgraph  2.34.2
29:   RaggedExperiment  1.24.2
30:               RCy3  2.20.1
31:              RedeR   2.4.3
32:       rhdf5filters  1.12.1
33:        rtracklayer  1.60.1
34:           S4Arrays   1.0.6
35:               safe  3.40.1
36:       ScaledMatrix   1.8.1
37:             scater  1.28.0
38:              scran  1.28.2
39:            scuttle  1.10.2
40:           SeqArray  1.40.1
41:  sparseMatrixStats  1.12.2
42:           STRINGdb  2.12.1
43:        systemPipeR   2.6.3
44:        trackViewer  1.36.2
45:             treeio  1.24.3
46:          tweeDEseq  1.46.2
47:     universalmotif  1.18.1
               Package Version
> 
```

**Comment by eddelbuettel** [comment]
Done for jammy, will do focal next.

Thanks for the heads-up, this was an oversight and is something that clearly improves the overall experience!

**Comment by eddelbuettel** [comment]
Now also taken care of for focal.  Thanks again.
