### ISSUE TITLE
devEMF has graphics API version mismatch with current R

### ISSUE THREAD

**Issue by ppc-it** [eddelbuettel/r2u#45]
Using the r2u version of devEMF 4.4.1 reports the following issue when using it with R 4.3.1 in Docker:

Error in emf(file = Filenameemf, width = width, height = height,  : 
  Graphics API version mismatch

This seems similar to the issue https://github.com/eddelbuettel/r2u/issues/42

**Comment by eddelbuettel** [comment]
Thanks for the heads-up -- it requires a rebuild for R 4.3.* which I just triggered for both 20.04 and 22.04.  A few other packages implementing graphics devices had been covered, this one slipped.

Please try the new binaries ending in .2; an `apt update` should get the respective package for you.
