### ISSUE TITLE
Alternative mirrors?

### ISSUE THREAD

**Issue by courtiol** [eddelbuettel/r2u#47]
The "well-connected main mirror" is rather slow far away from Illinois.
Are there alternative mirrors available?
(I am personally in Germany)

**Comment by eddelbuettel** [comment]
Well you are the first person to complain about this from Europe.  I actually tried it myself on vacation just days ago and found it to be fine.

"Historically" it was much: an early user had real issues to get to _my computer_ from New Zealand. That is much better now.  Also, note that these routes "vary" sometimes.  Maybe try again in a day or two.

Lastly, mirrors appear when someone contributes a host.  Would you have a place in Europe?

**Comment by courtiol** [comment]
Thanks a lot,
I think it was a temporary bottleneck along the route.
It was down to below 1mb/sec but indeed it is now very fast.
If the drop occurs frequently, I will try to convince a local university to host the mirror, but for now I close this issue :-)

**Comment by eddelbuettel** [comment]
I would also appreciate an email to CRAN to encourage them to mirror it :)
