### ISSUE TITLE
Different number of CRAN packages with `available.packages()`?

### ISSUE THREAD

**Issue by etiennebacher** [eddelbuettel/r2u#48]
Hi, I saw your recent announcements on Mastodon about the number of CRAN packages supported (~22k) and I was surprised because I thought the number of CRAN packages was around 20k. This is also what `available.packages()` returns:
``` r
nrow(available.packages())
#> [1] 19946
```
I'm simply curious, where does the difference come from? 

Many thanks for `r2u`!

**Comment by eddelbuettel** [comment]
Maybe I'll just add it to the FAQ vignette...

**Comment by etiennebacher** [comment]
> maybe you can suggested a place to add that.

You could put that after "This currently resuls in 22214 and 22120 binary packages from CRAN in "focal" and "jammy", respectively, and 391 and 391 BioConductor packages, respectively, from the 3.18 release." in the README

(btw, typo: "resuls" -> "results")

**Comment by eddelbuettel** [comment]
I just went over the FAQ vignette and added a paragraph there that'll go live in a bit.  (And the FAQ needed an update to another question too so all good) so maybe I just forward-reference this.  

Thanks also for finding the typo.  And thanks for, IIRC, also mentioning how r2u + r-universe-binaries-for-jammy are dynamite together!  Only sane way to get rpolars :grinning:  (as a 'mere casual user').

**Comment by eddelbuettel** [comment]
And done in https://github.com/eddelbuettel/r2u/commit/7370cdf0f9c892af1b52b1e1896255a206472cff

**Comment by etiennebacher** [comment]
Great! As always thanks for the super fast answer
