### ISSUE TITLE
Possible package missing from repo: r-cran-r2rtf

### ISSUE THREAD

**Issue by jmcastagnetto** [eddelbuettel/r2u#50]
Tried running an update on Ubuntu 22.04LTS today and got this error:

```{bash}
$ sudo apt update
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
...
Ign:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                 
...
Hit:14 http://archive.ubuntu.com/ubuntu jammy-backports InRelease                         
Get:18 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
...
Fetched 231 kB in 2s (146 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.

$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  r-cran-r2rtf
The following packages have been kept back:
  firmware-sof-signed
The following packages will be upgraded:
  r-cran-gsdesign
1 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 323 kB/1,764 kB of archives.
After this operation, 502 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://r2u.stat.illinois.edu/ubuntu jammy/main all r-cran-r2rtf all 1.1.0-1.ca2204.1
  404  Not Found [IP: 192.17.190.167 443]
E: Failed to fetch https://r2u.stat.illinois.edu/ubuntu/pool/dists/jammy/main/r-cran-r2rtf_1.1.0-1.ca2204.1_all.deb  404  Not Found [IP: 192.17.190.167 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

The strange thing is that I can get the deb file directly using a web browser and going to https://r2u.stat.illinois.edu/ubuntu/pool/dists/jammy/main/, but not with `wget` or `curl`.

**Comment by eddelbuettel** [comment]
I think you may have hot a temporary network snafu?  I just fired up the container to check and all seems well:

```
$ docker run --rm -ti rocker/r2u
root@ed16a26411ac:/# apt update -qqq
root@ed16a26411ac:/# apt-cache madison r-cran-r2rtf
r-cran-r2rtf | 1.1.1-1.ca2204.1 | https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages
root@ed16a26411ac:/# 
```

I also had no issue running `apt update; apt upgrade`.  Maybe try again?

**Comment by jmcastagnetto** [comment]
Yep, now all is good. Might have been a temporary glitch in the nginx for that container. 
Thanks!

**Comment by eddelbuettel** [comment]
(There is no nginx in the container, there is nginx over at the server, and yes, I have seen similar hickups before at GitHub Actions pulling from `apt` repos, or pulling launchpad when we used c2d4u, or even in normal apt usage.)

Yes, it is a recurring (though luckily rare) error condition for `apt`.  Once you've seen it a few times you know and just relaunch.  Sorry for the inconvenience :smile_cat:

**Comment by eddelbuettel** [comment]
And the weirdest thing is that (as I have access to the nginx logs and so look every now and then how it is doing) that we once shipped about three and a half million packages in two days (!!!) so I am still puzzled why the occassional request blibs.  Part of me things it may be other network hops in between but of course I don't really know ...  

But the server itself seems to be able to put up quite a fight so reason for worries there.

**Comment by jmcastagnetto** [comment]
Thank you for creating and keeping this very useful resource, makes life easier for *nix heads like me :-)

**Comment by eddelbuettel** [comment]
Yep eating (as the expression goes) "my own dogfood too" as I just used it to debug something under r-devel myself (and may end up publishing an 'r2u with r-devel' container / change an existing countainer to provide this).  

Thanks also for the toot and for spreading the word.  It's appreciated!
