### ISSUE TITLE
Problem with running install.packages()

### ISSUE THREAD

**Issue by peculiar97** [eddelbuettel/r2u#52]
Hi, 

After installing r2u, according to [this](https://github.com/eddelbuettel/r2u/blob/master/inst/scripts/add_cranapt_jammy.sh), in a clean R session inside Ubuntu terminal, when trying to install any packages e.g. :
`install.packages("BiocManager")`

I see the following error:

> Error: dbus: Call failed: Launch helper exited with unknown return code 1

I checked the **/var/log/syslog** and I found this error:

```r
Traceback (most recent call last):
 org.r_project.linux1[44262]:   File "/usr/local/lib/R/site-library/bspm/service/bspm.py", line 150, in <module>
 org.r_project.linux1[44262]:     read_conf()
 org.r_project.linux1[44262]:   File "/usr/local/lib/R/site-library/bspm/service/bspm.py", line 16, in read_conf
 org.r_project.linux1[44262]:     conf = backend.discover()
 org.r_project.linux1[44262]:   File "/usr/local/lib/R/site-library/bspm/service/backend/apt.py", line 15, in discover
 org.r_project.linux1[44262]:     cache_update(partial(cache.update, aprogress), force=True)
org.r_project.linux1[44262]:   File "/usr/local/lib/R/site-library/bspm/service/backend/_utils.py", line 33, in cache_update
 org.r_project.linux1[44262]:     method()
 org.r_project.linux1[44262]:   File "/usr/lib/python3/dist-packages/apt/cache.py", line 573, in update
org.r_project.linux1[44262]:     raise FetchFailedException(e) 
dbus-daemon[726]: [system] Activated service 'org.r_project.linux1' failed: Launch helper exited with unknown return code 1
```

The R version is 
`R version 4.3.2 (2023-10-31) -- "Eye Holes"`

The operating system:
`Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
`

Any help would be greatly appreciated!

**Comment by eddelbuettel** [comment]
Hi there, and thanks for trying r2u!

I can take a closer look later but this looks _very much_ like a standard issue of not being able to dispatch to `bspm` ... because `bspm` was not installed as root.  Check a few of our older issue tickets, check the `bspm` repo and its issues, and just do 

    sudo Rscript -e `bspm::dispable(); install.packages("bspm")`

after which `bspm`, as a key part, should be back 'at system level' and be able to talk to `dpkg` and `apt` via `systemd`.

**Comment by peculiar97** [comment]
Dear Dirk, 
Thanks for your prompt answer.

For Installation of **bspm** I followed the instructions at [bspm reop for ubuntu](https://github.com/cran4linux/bspm?tab=readme-ov-file#ubuntu). and I run all the codes as the root.

Runnnig this code
`sudo Rscript -e 'bspm::dispable(); install.packages("bspm")'`

gave 

> Tracing function "install.packages" in package "utils"
Error: 'dispable' is not an exported object from 'namespace:bspm'
Execution halted

I should also add if I install the packages by **apt** e.g.
`sudo apt install r-cran-ggplot2`
everything is OK!

But I am not able to use  **install.packages**.

**Comment by eddelbuettel** [comment]
That was my typo which gets the error.  My apologies.  Please try again with

    sudo Rscript -e 'bspm::disable(); install.packages("bspm")'

(`bspm` has only two user-facing function `enable()` and `disable()`, I fat-fingered.)

That you _can in fact_ install via `apt` proves my point:  your setup is correct, you have the correct repo entries -- we just have to ensure the added cherry of `bspm` is installed just right so that it can elevate the R installation request to a system command.  You are close.

**Comment by peculiar97** [comment]
I got surprised since there is no **dispable()** ;)

trying the corrected code 
`sudo Rscript -e 'bspm::disable(); install.packages("bspm")'`

and then running 
`install.packages("BiocManager")`

gave 

> Hit https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease                                       
Hit http://security.ubuntu.com/ubuntu jammy-security InRelease                                                 
Hit https://dl.google.com/linux/chrome/deb stable InRelease                                                    
Hit https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease                               
Hit https://packages.microsoft.com/repos/edge stable InRelease                                                 
Hit http://pl.archive.ubuntu.com/ubuntu jammy InRelease                                                        
Get:1 https://ppa.launchpadcontent.net/eugenesan/ppa/ubuntu jammy InRelease [17.5 kB]                          
Hit https://download.sublimetext.com apt/stable/ InRelease                                                     
Hit http://pl.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                
Get:2 https://ppa.launchpadcontent.net/marutter/rrutter4.0/ubuntu jammy InRelease [17.5 kB]                    
Hit http://pl.archive.ubuntu.com/ubuntu jammy-backports InRelease                                              
Ign https://ppa.launchpadcontent.net/nomacs/stable/ubuntu jammy InRelease                                      
Ign https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy InRelease                                 
Hit https://ppa.launchpadcontent.net/slgobinath/safeeyes/ubuntu jammy InRelease                                
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                       
Hit https://ppa.launchpadcontent.net/ubuntuhandbook1/audacity/ubuntu jammy InRelease                           
Err https://ppa.launchpadcontent.net/nomacs/stable/ubuntu jammy Release                                        
  404  Not Found [IP: 185.125.190.80 443]                                                                      
Err https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release                                   
  404  Not Found [IP: 185.125.190.80 443]                                                                      
Hit https://r2u.stat.illinois.edu/ubuntu jammy Release                                                         
Fetched 35.0 kB in 0s (0 B/s)                                                                                  
Error:

**Comment by eddelbuettel** [comment]
Closer!!  Any idea why launchpad times out?

(Also: formatting trick here.  Use three backticks, followed a languages symbol so eg 

``````
```r
res <- lm(y ~ x, data=D)
```
``````

will produce

```r
res <- lm(y ~ x, data=D)
```

**Comment by eddelbuettel** [comment]
But to prove the point over here things are peachy -- using Docker just to simulate an 'empty' system:

```sh
edd@rob:~$ docker run --rm -ti rocker/r2u Rscript -e 'install.packages("BiocManager")'
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                                                                          
Get:1 https://r2u.stat.illinois.edu/ubuntu jammy Release [5713 B]                                                                                                                                                 
Get:2 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]                                                                                                                                              
Get:3 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2429 kB]                                                                                                                                    
Get:4 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                                                                                                                   
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                                                                         
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [7714 kB]                                                                                                                                      
Get:7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3626 B]                                                                                                                               
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [48.6 kB]                                                                                                                               
Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1046 kB]                                                                                                                          
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                                                                                          
Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]                                                                                                                                        
Get:12 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]                                                                                                                                  
Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]                                                                                                                                   
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1572 kB]                                                                                                                       
Get:15 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]                                                                                                                       
Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1326 kB]                                                                                                                             
Get:17 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]                                                                                                                                  
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]                                                                                                                                       
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1599 kB]                                                                                                                               
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1602 kB]                                                                                                                         
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]                                                                                                                         
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1305 kB]                                                                                                                           
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [28.1 kB]                                                                                                                         
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [50.4 kB]                                                                                                                             
Fetched 39.1 MB in 0s (0 B/s)                                                                                                                                                                                     
Install system packages as root...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
Reading state information... Done
Get:1 https://r2u.stat.illinois.edu/ubuntu jammy/main all r-cran-biocmanager all 1.30.22-1.ca2204.1 [479 kB]                                                                                                      
Fetched 479 kB in 0s (0 B/s)                                                                                                                                                                                      
Selecting previously unselected package r-cran-biocmanager.
(Reading database ... 18320 files and directories currently installed.)
Preparing to unpack .../r-cran-biocmanager_1.30.22-1.ca2204.1_all.deb ...
Unpacking r-cran-biocmanager (1.30.22-1.ca2204.1) ...
Setting up r-cran-biocmanager (1.30.22-1.ca2204.1) ...
edd@rob:~$ 
```

**Comment by peculiar97** [comment]
So far so good!
Runnig 
`sudo docker run --rm -ti rocker/r2u Rscript -e 'install.packages("BiocManager")'
Unable to find image 'rocker/r2u:latest' locally
latest: Pulling from rocker/r2u
e96e057aae67: Pull complete 
a8390eea866c: Pull complete 
145fd72d096e: Pull complete 
Digest: sha256:ad84e9056a4b097c162124a62f5d3d15c86a8297d1e632810e2d591cd57ce05b
Status: Downloaded newer image for rocker/r2u:latest
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3626 B]                                                                       
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                 
Get:3 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                                                           
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                                   
Get:5 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1046 kB]                                                                  
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]                                                                                 
Get:7 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]                                                                           
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [48.6 kB]                                                                       
Get:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]                                                                            
Get:10 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]                                                               
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1326 kB]                                                                     
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1572 kB]                                                               
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                  
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy Release [5713 B]                                                                                        
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]                                                                                     
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2429 kB]                                                                           
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]                                                                               
Get:17 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]                                                                          
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1307 kB]                                                                   
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1606 kB]                                                                       
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]                                                                 
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1611 kB]                                                                 
Get:22 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [28.1 kB]                                                                 
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [50.4 kB]                                                                     
Get:24 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [7714 kB]                                                                             
Fetched 39.1 MB in 6s (5906 kB/s)                                                                                                                         
Install system packages as root...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
Reading state information... Done
Get:1 https://r2u.stat.illinois.edu/ubuntu jammy/main all r-cran-biocmanager all 1.30.22-1.ca2204.1 [479 kB]                                              
Fetched 479 kB in 0s (0 B/s)                                                                                                                              
Selecting previously unselected package r-cran-biocmanager.
(Reading database ... 18320 files and directories currently installed.)
Preparing to unpack .../r-cran-biocmanager_1.30.22-1.ca2204.1_all.deb ...
Unpacking r-cran-biocmanager (1.30.22-1.ca2204.1) ...
Setting up r-cran-biocmanager (1.30.22-1.ca2204.1) ...
`

**Comment by eddelbuettel** [comment]
If on your 'real' system some `apt` repos give you errors you can always _temporarily_ comment them out.  These issues are really orthogonal to your use of `bspm` and we should get that issu squashed.   The other one may be a tempoary glitch.

**Comment by peculiar97** [comment]
Inside the rstudio, still I get dbus error!
```r
> install.packages("BiocManager")
Error in install.packages : dbus: Call failed: Launch helper exited with unknown return code 1
> install.packages("rmarkdown")
Error in install.packages : dbus: Call failed: Launch helper exited with unknown return code 1
```
This is my R session info 
```r
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2 tools_4.3.2    bspm_0.5.5  
```

**Comment by eddelbuettel** [comment]
Maybe search the old issues, and/or search at the `bspm` repo.  There was a reason for something, and as I recall also a workaround -- maybe again the 'did you install `bspm` as root' ?  

At one point I thought it would not work at all but that is not true.  All I can tell you is 'it works here'.

**Comment by eddelbuettel** [comment]
Quick 'proof' from my laptop after first uninstalling a package to be able to show an actual installation:

![image](https://github.com/eddelbuettel/r2u/assets/673121/4d201c2f-d9b4-42a5-9261-68d02a9de064)

**Comment by peculiar97** [comment]
Bspm is installed as root.

Interestingly, when I disable bspm
```r
bspm::disable()
install.packages("BiocManager")
```
it works as a charm and starts installing the desired package.

**Comment by eddelbuettel** [comment]
That could have been it.  _Maybe_ I have `~/.Rprofile` set up in such a way that I do not enable `bspm`.

But then .... if it doesn't use bspm, it doesn't use r2u?

**Comment by peculiar97** [comment]
But it seems bspm is still running in background

```r
bspm::disable()
install.packages("BiocManager")
Installing package into ‘/home/mah/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/BiocManager_1.30.22.tar.gz'
Content type 'application/x-gzip' length 582690 bytes (569 KB)
==================================================
downloaded 569 KB

Tracing function "install.packages" in package "utils"
Tracing function "install.packages" in package "utils"
* installing *source* package ‘BiocManager’ ...
** package ‘BiocManager’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Tracing function "install.packages" in package "utils"
Tracing function "install.packages" in package "utils"
** help
*** installing help indices
** building package indices
Tracing function "install.packages" in package "utils"
Tracing function "install.packages" in package "utils"
** installing vignettes
** testing if installed package can be loaded from temporary location
Tracing function "install.packages" in package "utils"
Tracing function "install.packages" in package "utils"
** testing if installed package can be loaded from final location
Tracing function "install.packages" in package "utils"
Tracing function "install.packages" in package "utils"
** testing if installed package keeps a record of temporary installation path
* DONE (BiocManager)

The downloaded source packages are in
	‘/tmp/RtmpKqm1Tx/downloaded_packages
```

**Comment by eddelbuettel** [comment]
Ok, only you are on your machine.  Maybe you followed my advice and added `bspm::enable()` to `/etc/R/Profile` ? Then fresh R session will be using it, and you see the `Tracing ...` messages you quote.

`bspm` is good. You need _if_ you want `install.packages()` to call `apt`.

As also stated, `bspm` must also be installed correctly (as `root` user) to be able to do that.  That is about all I can repeat to you.  Some of the rest you may have to debug locally.

**Comment by eddelbuettel** [comment]
Ok, only you are on your machine.  Maybe you followed my advice and added `bspm::enable()` to `/etc/R/Profile` ? Then fresh R session will be using it, and you see the `Tracing ...` messages you quote.

`bspm` is good. You need _if_ you want `install.packages()` to call `apt`.

As also stated, `bspm` must also be installed correctly (as `root` user) to be able to do that.  That is about all I can repeat to you.  Some of the rest you may have to debug locally.

But something seems wrong at your end.  You have both `install.packages()` traced _and_ local installation from `source`.  But I am out of ideas about what may be different.

**Comment by eddelbuettel** [comment]
One idea: try running `Rscript -e 'bspm::shadowed_packages()'`.  It may reveal multiple `bspm` installations. Or maybe the one you made as `root` when into `root`'s own local installation path.

**Comment by peculiar97** [comment]
Tried running shawdow_packages, but nothing came out 
```r
sudo Rscript -e 'bspm::shadowed_packages()'
[1] Package        LibPath        Version        Shadow.LibPath Shadow.Version
[6] Shadow.Newer  
<0 rows> (or 0-length row.names)
```
Evenmore, I tried to remove all the possible installation of "bspm" using 
```r
library(utils)

# Remove the package
remove.packages("bspm")

# If the package is installed in multiple libraries,  specify the library path
# Get the library path
path.lib <- .libPaths()

# Remove the package from a specific library
remove.packages("bspm", lib = path.lib[1])  # change the index based on your library path
```
and reinstalled using the source version 
```r
sudo R CMD INSTALL bspm_0.5.5.tar.gz
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘bspm’ ...
** package ‘bspm’ successfully unpacked and MD5 sums checked
** using staged installation
* installing /usr/share/dbus-1/system-services/org.r_project.linux1.service
* installing /etc/dbus-1/system.d/org.r_project.linux1.conf
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (bspm)
```
Still I see the dbus error after enabling the bspm.

Anyway, Dirk thank you very much for the brainstorming and your feedback!

**Comment by eddelbuettel** [comment]
Can we recap _completely_ what works and does not work on your machine?

1.  You can install via `apt` i.e. `sudo apt install r-cran-ggplot2` works (and preferably the logs show it being installed from r2u not plain ubuntu (per the download path) and the version number is 3.4.4-1.ca2204.1
2.  You can or cannot install via `bspm` and then `apt` outside of RStudio?  Does `Rscript -e 'install.packages("ggplot2")'` fetch that same binary?  (You may have to uninstall, which may be tricky because of depends so maybe play with a 'leaf' package with no dependencies like `fortunes`).
3.  You cannot install from RStudio

One issue could be that you lack the Python packages `bspm` needs:   python3-apt, python3-dbus, python3-gi  -- Do you have those?

**Comment by peculiar97** [comment]
For your record, I prepared real-time answers for the questions

> 1. You can install via `apt` i.e. `sudo apt install r-cran-ggplot2` works (and preferably the logs show it being installed from r2u not plain ubuntu (per the download path) and the version number is 3.4.4-1.ca2204.1

```r
sudo apt install r-cran-ggplot2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-cran-ggplot2 is already the newest version (3.4.4-1.ca2204.1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
```

> 2. You can or cannot install via bspm and then apt outside of RStudio? Does Rscript -e 'install.packages("ggplot2")' fetch that same binary? (You may have to uninstall, which may be tricky because of depends so maybe play with a 'leaf' package with no dependencies like fortunes).
```r
sudo Rscript -e 'install.packages("ggplot2")'
Hit http://pl.archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                                               
Hit http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                                                        
Hit http://pl.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                                                                                       
Hit http://pl.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                                                                                     
Hit https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                          
Hit https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease                                                                                                                              
Hit https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                           
Hit https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease                                                                                                                      
Hit https://ppa.launchpadcontent.net/eugenesan/ppa/ubuntu jammy InRelease                                                                                                                             
Hit https://download.sublimetext.com apt/stable/ InRelease                                                                                                                                            
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                                                              
Hit https://ppa.launchpadcontent.net/marutter/rrutter4.0/ubuntu jammy InRelease                                                                                                                       
Ign https://ppa.launchpadcontent.net/nomacs/stable/ubuntu jammy InRelease                                                                                                                             
Hit https://r2u.stat.illinois.edu/ubuntu jammy Release                                                                                                                                                
Ign https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy InRelease                                                                                                                        
Hit https://packages.microsoft.com/repos/edge stable InRelease                                                                                                                                        
Hit https://ppa.launchpadcontent.net/slgobinath/safeeyes/ubuntu jammy InRelease                                                                                                                       
Hit https://ppa.launchpadcontent.net/ubuntuhandbook1/audacity/ubuntu jammy InRelease                                                                                                                  
Err https://ppa.launchpadcontent.net/nomacs/stable/ubuntu jammy Release                                                                                                                               
  404  Not Found [IP: 185.125.190.80 443]                                                                                                                                                             
Err https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release                                                                                                                          
  404  Not Found [IP: 185.125.190.80 443]                                                                                                                                                             
Fetched 0 B in 0s (0 B/s)                                                                                                                                                                             
Error: 
Execution halted
```

> 3.You cannot install from RStudio
```r
install.packages("ggplot2")
Error in install.packages : dbus: Call failed: Launch helper exited with unknown return code 1
```

> One issue could be that you lack the Python packages bspm needs: python3-apt, python3-dbus, python3-gi -- Do you have those?
```r
dpkg -s python3-apt python3-dbus python3-gi
Package: python3-apt
Status: install ok installed
Priority: important
Section: python
Installed-Size: 705
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: allowed
Source: python-apt
Version: 2.4.0ubuntu2
Replaces: python-apt (<< 0.7.98+nmu1)
Provides: python3.10-apt
Depends: python3 (<< 3.11), python3 (>= 3.10~), python3:any, libapt-pkg6.0 (>= 1.9.11~), libc6 (>= 2.33), libgcc-s1 (>= 3.3.1), libstdc++6 (>= 11), python-apt-common, distro-info-data
Recommends: lsb-release, iso-codes
Suggests: python3-apt-dbg, python-apt-doc, apt
Breaks: apt-xapian-index (<< 0.51~), kthresher (<= 1.4.0-1), python-apt (<< 0.7.98+nmu1)
Description: Python 3 interface to libapt-pkg
 The apt_pkg Python 3 interface will provide full access to the internal
 libapt-pkg structures allowing Python 3 programs to easily perform a
 variety of functions, such as:
 .
  - Access to the APT configuration system
  - Access to the APT package information database
  - Parsing of Debian package control files, and other files with a
    similar structure
 .
 The included 'aptsources' Python interface provides an abstraction of
 the sources.list configuration on the repository and the distro level.
Original-Maintainer: APT Development Team <deity@lists.debian.org>

Package: python3-dbus
Status: install ok installed
Priority: important
Section: python
Installed-Size: 417
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: dbus-python
Version: 1.2.18-3build1
Provides: python3.10-dbus
Depends: python3 (<< 3.11), python3 (>= 3.10~), python3:any, libc6 (>= 2.4), libdbus-1-3 (>= 1.9.14), libglib2.0-0 (>= 2.40)
Recommends: python3-gi
Suggests: python-dbus-doc
Description: simple interprocess messaging system (Python 3 interface)
 D-Bus is a message bus, used for sending messages between applications.
 Conceptually, it fits somewhere in between raw sockets and CORBA in
 terms of complexity.
 .
 This package provides a Python 3 interface to D-Bus.
 .
 See the dbus description for more information about D-Bus in general.
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Homepage: https://www.freedesktop.org/wiki/Software/DBusBindings#Python

Package: python3-gi
Status: install ok installed
Priority: important
Section: python
Installed-Size: 747
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: allowed
Source: pygobject
Version: 3.42.1-0ubuntu1
Depends: gir1.2-glib-2.0 (>= 1.48.0), python3 (<< 3.11), python3 (>= 3.10~), python3:any, libc6 (>= 2.14), libffi8 (>= 3.4), libgirepository-1.0-1 (>= 1.62.0-4~), libgirepository-1.0-1-with-libffi8 (>= 1.62.0-4~), libglib2.0-0 (>= 2.56.0)
Description: Python 3 bindings for gobject-introspection libraries
 GObject is an abstraction layer that allows programming with an object
 paradigm that is compatible with many languages. It is a part of Glib,
 the core library used to build GTK+ and GNOME.
 .
 This package contains the Python 3 binding generator for libraries that
 support gobject-introspection, i. e. which ship a gir1.2-<name>-<version>
 package. With these packages, the libraries can be used from Python 3.
Homepage: https://wiki.gnome.org/Projects/PyGObject
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
```

**Comment by eddelbuettel** [comment]
1) is good

2) fails for the reason I told you about yesterday and which you can fix but haven't, you seem to have apt entries pointing to repositories which no longer supply a PACKAGES file.  That is not a bspm issue.

3) also good.

I am out of ideas now, sorry.  Paging @enchufa2 who may have clearer eyes and may spot something I missed.

**Comment by peculiar97** [comment]
> 2\. fails for the reason I told you about yesterday and which you can fix but haven't, you seem to have apt entries pointing to repositories which no longer supply a PACKAGES file.  That is not a bspm issue.

Sorry, I did not get that. Do you suggest this workaround? 
```r
sudo Rscript -e 'bspm::disable(); install.packages("ggplot2")'
```

**Comment by eddelbuettel** [comment]
Quoting from your second post that showed that:

```
sudo Rscript -e 'install.packages("ggplot2")'
Hit http://pl.archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                                               
Hit http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                                                        
Hit http://pl.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                                                                                       
Hit http://pl.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                                                                                     
Hit https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                          
Hit https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease                                                                                                                              
Hit https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                           
Hit https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease                                                                                                                      
Hit https://ppa.launchpadcontent.net/eugenesan/ppa/ubuntu jammy InRelease                                                                                                                             
Hit https://download.sublimetext.com apt/stable/ InRelease                                                                                                                                            
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                                                              
Hit https://ppa.launchpadcontent.net/marutter/rrutter4.0/ubuntu jammy InRelease                                                                                                                       
Ign https://ppa.launchpadcontent.net/nomacs/stable/ubuntu jammy InRelease                                                                                                                             
Hit https://r2u.stat.illinois.edu/ubuntu jammy Release                                                                                                                                                
Ign https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy InRelease                                                                                                                        
Hit https://packages.microsoft.com/repos/edge stable InRelease                                                                                                                                        
Hit https://ppa.launchpadcontent.net/slgobinath/safeeyes/ubuntu jammy InRelease                                                                                                                       
Hit https://ppa.launchpadcontent.net/ubuntuhandbook1/audacity/ubuntu jammy InRelease                                                                                                                  
Err https://ppa.launchpadcontent.net/nomacs/stable/ubuntu jammy Release                                                                                                                               
  404  Not Found [IP: 185.125.190.80 443]                                                                                                                                                             
Err https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release                                                                                                                          
  404  Not Found [IP: 185.125.190.80 443]                                                                                                                                                             
Fetched 0 B in 0s (0 B/s)                                                                                                                                                                             
Error: 
Execution halted
```

IP address 185.125.190.80 is launchpadcontent.net.  I recommend you comment out the entries leading to the 404 which in turn leads to 'Error: Execution halted'.  We want to avoid such errors so that we can refresh `apt` indices and use it.

**Comment by Enchufa2** [comment]
I'm out of ideas too. Could you @peculiar97 please share the output of

```bash
Rscript -e '.libPaths()'
```

and 

```bash
sudo Rscript -e '.libPaths()'
```

?

**Comment by peculiar97** [comment]
@eddelbuettel is right! the culprits were these troublesome repos that led to "404  Not Found" error. Commenting out these repos solved the problem!

Thanks @eddelbuettel & @Enchufa2  for making such a responsive community around r2u & bspm.

**Comment by eddelbuettel** [comment]
Yay!  Annoying that such a little hickup can block things, isn't it?  The error message is not the greatest but it does say 'error' so we are being warned ...

Glad you are up and running with r2u.  I am continuing to get a lot of use out of it, and having `bspm` makes it so much nicer too.
