### ISSUE TITLE
Please update 10 CRAN packages and 1 Bioconductor package

### ISSUE THREAD

**Issue by aitap** [eddelbuettel/r2u#54]
Thank you for your work on packaging so many R packages for Ubuntu! As you said in your e-mail, I'm reporting a few that are currently a bit behind CRAN and Bioconductor:

```r
setRepositories(ind=1:4) # CRAN & BioC
subset(
 merge(
  available.packages(), installed.packages(),
  by = 'Package', suffixes=c('.available', '.installed')
 ),
 Version.available > Version.installed
)[,c('Package','Repository')]
#              Package                                              Repository
# 24          antiword                 https://cloud.r-project.org/src/contrib
# 154             coda                 https://cloud.r-project.org/src/contrib
# 163       commonmark                 https://cloud.r-project.org/src/contrib
# 197       data.table                 https://cloud.r-project.org/src/contrib
# 237          distrEx                 https://cloud.r-project.org/src/contrib
# 264            edgeR https://bioconductor.org/packages/3.18/bioc/src/contrib
# 511           igraph                 https://cloud.r-project.org/src/contrib
# 612          littler                 https://cloud.r-project.org/src/contrib
# 697  MplusAutomation                 https://cloud.r-project.org/src/contrib
# 1145              sp                 https://cloud.r-project.org/src/contrib
# 1225       tidygraph                 https://cloud.r-project.org/src/contrib
```

I can see `r-cran-littler` being available in `https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/`, but the one in `https://r2u.stat.illinois.edu/ubuntu jammy/main` has a larger APT priority on the `docker.io/rocker/r2u` container.

**Comment by eddelbuettel** [comment]
Please see CRANBerries (https://dirk.eddelbuettel.com/cranberries/, or via RSS, or Mastodon toots, or Bsky skeets) -- most of these _came to CRAN yesterday_ as I can tell from eyeballing:  `antiword`, `commonmark`, `data.table`, `igraph`.

`littler` is special, I am the author, it comes borked from p3m so we do it apart. It should still be working and current, and the fact that Michael also kindly covers it at jammy-cran40 is irrelevant.   

So I am going to close this.  When you claim "oh bad bad r2u these packages are behind" also included their CRAN release date.  That is in either `available.packages()` or `utils::CRAN_package_db()` and I of course know that you are able to do an inner join.

I appreciate the effort in tryying to help and improve r2y but this fell short.

**Comment by eddelbuettel** [comment]
And to be plain:  You cannot expect an hourly cadence from us as r-universe does.  We give you over 22k packages, working, with full dependencies, for two LTS releases -- but updates need a day or two (or a weekend) or longer if p3m is behind.  Such is life.  You can always add packages from source if you need them _immediately_.  I may add this to the FAQ.

I triggered a BioC update:  `basililisk` + `edgeR` + `tximeta` updated and are now available for focal and jammy.

**Comment by aitap** [comment]
Sorry, I should have stopped to think and check the dates.

**Comment by eddelbuettel** [comment]
No worries -- as I also lived off source on Linux for 25+ year I am also in the habit of expected new packages "immediately".  

We may want to build ourselves a little package lister / checker with data.  Inaki (in his `bspm`) and I (in my `dang`) wrote something for 'shadowed packages' (to identify when `bspm`-installed binaries in `/usr/lib/R/site-library` are "shadowed" by possible older packages in ``/usr/local/lib/R/site-library`.  And I play a little with dates in eg issue 391 for RcppArmadillo which managed the long transition.  So we could do a local package checker that lists 'newer available at CRAN' and flags when it is several day out.  Would also help with QA.

Thoughts?

You must already have something similar to find the set you reported, no?
