### ISSUE TITLE
Enhancement: Timeline for support of Ubuntu 24.04LTS?

### ISSUE THREAD

**Issue by jmcastagnetto** [eddelbuettel/r2u#56]
Filling this issue just to keep it in the radar. I know that this version of Ubuntu has been released yesterday :-). 

So far, I've upgraded one of my Linux boxes to 24.04LTS but manually kept pointing to the 22.04 r4u packages, and everything seems to be working, so there is no rush.

**Comment by eddelbuettel** [comment]
It'll be ready when it's ready :)   

It's a one-person project, and I have some other obligations. I want this to happen soon but please do think 'months' not 'hours'.  It usually takes @marutter and myself several weeks just to update the R binaries and key packages.

**Comment by jmcastagnetto** [comment]
Sure thing, no rush, life has precedence :-)

**Comment by eddelbuettel** [comment]
Per the skeet below this is now available.

![image](https://github.com/eddelbuettel/r2u/assets/673121/741ca9a7-622e-4ec6-ab69-fd3ad79d8ede)
