### ISSUE TITLE
Problems with R 4.4 and BiocManager

### ISSUE THREAD

**Issue by jmgs7** [eddelbuettel/r2u#58]
Hi, I just updated to R 4.4, and BiocManager requieres me to upgrade to 3.19. The problem is the packages provided in r2u are for BiocManager 1.18, and it is impossible to install Bioconductor packages that are not packaged in the r2u repos (clustifyr in my case).

I tried updating BiocManager with  BiocManager::install(version="3.19") but still shows the "please upgrade to BiocManager 3.19" afterwards.

![image](https://github.com/eddelbuettel/r2u/assets/30865599/de5ca5c0-1acb-4cf5-b66d-f278c7d2076c)

Any plans to upgrade to BiocManager 1.19?

Best regards.

**Comment by eddelbuettel** [comment]
Yes we will upgrade to 3.19, just how we moved to 3.17 and 3.18 before.

But I first have to upgrade to Ubuntu 24.04 which will take a moment too so this will be be imminent.  

(Also, and while it has been a moment, I do not think BiocManager "forces" you.  It just defaults to an update.  You should be able to continue with 3.18 if you select it.)

**Comment by eddelbuettel** [comment]
Per the skeet below, a new version of r2u is available, and it covers what was asked for here.

![image](https://github.com/eddelbuettel/r2u/assets/673121/0e298c86-ef0b-443e-9ef8-c071ffaeef03)
