### ISSUE TITLE
Error on installing stringi

### ISSUE THREAD

**Issue by bshor** [eddelbuettel/r2u#59]
I am running Debian 12 and trying to use r2u and bspm to install packages. I followed all the installation 

Some packages install, but many fail. Here I try to install stringr:

```
install.packages("stringr")
Install system packages...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
Reading state information... Done
Fetched 0 B in 0s (0 B/s)                                                       
Error in install.packages : dbus: Call failed: installArchives() failed
```
When I try to install it from the terminal, I get a "broken package" error.

```
sudo apt install r-cran-stringr
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-stringi : Depends: libicu70 (>= 70.1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

So perhaps it is only a problem with stringi dependency on libicu70?

**Comment by eddelbuettel** [comment]
> I am running Debian 12

Please see https://eddelbuettel.github.io/r2u/vignettes/FAQ/#can-i-use-current-r2u-with-debian

That said, the stringi issue / the libicu* issue also arises at time when running (as I do) a newer-than-previous LTS mixed with LTS.  _As the builds are for an LTS_ you will get versioned, frequently changing libraries _from that LTS_ for which one generally does not have apt entry (but could add one, I think i once did) so the best bet (if you know what you are doing) is to just curl or wget in the missing .deb package and install it (which gets old if it has dependencies...).

**Comment by eddelbuettel** [comment]
Or just reinstall Ubuntu to take advantage of r2u too :wink:
