### ISSUE TITLE
package ‘XML’ was built under R version 4.4.0

### ISSUE THREAD

**Issue by ComeBurguburu** [eddelbuettel/r2u#62]
Hi,
I use a Docker image with R version 4.3.3
I installed with r2u repository the package r-cran-xml

When I load the package `XML` , I have this warning:
```
package ‘XML’ was built under R version 4.4.0
```

When I use XML package , I have this error:
```
could not find symbol "catch.aborts" in environment of the generic function
```

Notes that "catch.aborts" was introduce in R 4.4.0 and is not compatible with my version of R 4.3.3

Is there a way to install R packages from r2u with specific R version ?

**Comment by eddelbuettel** [comment]
No there is not -- we do not promises a 'magic time machine' to combine all CRAN package versions with all R versions. We provide the service, just like CRAN itself, for the _current (major) version of R_ and that is R 4.4.*.

So this is out of scope here and I believe we also documented this.  The p3m.dev repo may offer you something for R 4.3.*.
