### ISSUE TITLE
Is it necessary to install bspm through R?

### ISSUE THREAD

**Issue by GreatEmerald** [eddelbuettel/r2u#63]
In the readme, it suggests installing the `bspm` package through R:

https://github.com/eddelbuettel/r2u/blob/05f53717df26b42800ae69444b2ece7bdd526492/README.md?plain=1#L189

However, in the previous steps, the r2u and CRAN repositories have been added to the system. Wouldn't it be simpler to make use of that and thus do:

```bash
apt-get install r-cran-bspm
```

Or is there any particular reason why it needs to be installed through R?

For context, I'm making an Ansible script to install r2u to automate the deployment, and to me it would make more sense to use apt rather than having to call R at that point.

**Comment by eddelbuettel** [comment]
Yes you should. The .deb I create for CRAN `bspm` is not good enough.  The 'meta reason' is that `bspm` does some magic that needs more Python and system integration so the recommendation (also at the `bspm` repo) is to, if in doubt, do `sudo Rscript -e 'install.packages("bspm")'` for which one (depending on what is turned on on your system may also need the variant `sudo Rscript -e 'bspm::disable(); install.packages("bspm")'` to ensure you really get a source installation.

Let me know if I should make that clearer in the docs.  

In setups where I can control this (eg Docker) I do add an explicit step to make sure this works. You Ansible script likely needs the same.

/cc @enchufa2

**Comment by GreatEmerald** [comment]
Indeed, if I do it only via apt, then any `install.packages` call results in an error about not being able to launch dbus. Installing the package through R works. That's a bit unfortunate because it means that either I have to somehow code an extra step to check if the package is already installed, or have the package get reinstalled every time I run the Ansible script. But oh well, at least the rest worked flawlessly, and the packages get installed in a flash now :)

**Comment by GreatEmerald** [comment]
I managed to make an Ansible script for it now, for reference you can find it here: https://github.com/GeoScripting-WUR/InstallLinuxScript/blob/master/noble/virtualbox.yml
The integration with systemd sounds like an interesting thing to look into, but unfortunately no time at the moment, so the extra step will suffice for now!

**Comment by eddelbuettel** [comment]
You have the `systemd` integration via `bspm` when installed as `root` via R. You're good.
