### ISSUE TITLE
Unable to install CRAN package in Ubuntu22.04 image - "Release file not found" in jammy-cran40/ issue

### ISSUE THREAD

**Issue by Venkatesh2523** [eddelbuettel/r2u#65]
Hi Team, 

**Description:**
I have been working on image building with Data Science libraries. As part of that I was supposed install CRAN_R module into our image. But when image trying to to "apt-get update" facing below issue. Can you someone help me in providing alternative ways / solutions for this issue.

**Error:**
**sudo apt-get update**
Get:1 file:/var/cuda-repo-ubuntu2204-12-2-local  InRelease [1572 B]
Get:1 file:/var/cuda-repo-ubuntu2204-12-2-local  InRelease [1572 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2204-9.1.1  InRelease [1572 B]
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Get:2 file:/var/cudnn-local-repo-ubuntu2204-9.1.1  InRelease [1572 B]
Hit:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Get:8 https://packages.microsoft.com/repos/azure-cli jammy InRelease [3596 B]
Ign:9 https://ppa.launchpadcontent.net/cran/libgit2/ubuntu jammy InRelease
Ign:10 https://ppa.launchpadcontent.net/cran/libgit2/ubuntu/dists devel-cran40/ InRelease
Err:11 https://ppa.launchpadcontent.net/cran/libgit2/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.80 443]
Get:12 https://packages.microsoft.com/repos/azure-cli jammy/main all Packages [1099 B]
Get:13 https://packages.microsoft.com/repos/azure-cli jammy/main amd64 Packages [1681 B]
Err:14 https://ppa.launchpadcontent.net/cran/libgit2/ubuntu/dists devel-cran40/ Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists...
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://ppa.launchpadcontent.net/cran/libgit2/ubuntu jammy Release' does not have a Release file.
W: https://packages.microsoft.com/repos/azure-cli/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://ppa.launchpadcontent.net/cran/libgit2/ubuntu/dists devel-cran40/ Release' does not have a Release file.
Aborting due to failures in fabfile; status code: 100

**Expected behavior:** System packages should get updated.

**Comment by eddelbuettel** [comment]
This is not an r2u issue. You appear to have issues with some of the `apt`-getable repos at launchpad.net.  You need to sort out if they still provide jammy.

The `404 Not Found [IP: 185.125.190.80 443]` indicates network issue. That has happened before to me too (say in CI at GitHub Actions) when the host was _temporarily_ down.  But again, not a systematic issue.

But as you can see below `r2u` on hammy is fine. It does not talk to launchpad.net:

```sh
edd@rob:~$ docker run --rm -ti rocker/r2u:jammy bash
root@e2bb0458816c:/# apt update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Ign:2 https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                                      
Get:3 https://r2u.stat.illinois.edu/ubuntu jammy Release [5,713 B]                                                                                                              
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]                                                          
Get:5 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                              
Get:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,104 kB]
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,551 kB]
Get:9 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [55.6 kB]                      
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,200 kB]                                                             
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [2,771 kB]                     
Get:12 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.7 kB]                                 
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,129 kB]                                     
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]                                                          
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [51.8 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [2,858 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,378 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,420 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [81.0 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [33.7 kB]
Fetched 44.0 MB in 3s (14.7 MB/s)                             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
44 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@e2bb0458816c:/# 
```

Another machine that uses a repo on launchpad.net just accessed that fine so if that server was down it was temporary.  So I am closing this now -- please feel free to reopen if you find something where r2u needs a fix or adjustment.

**Comment by Venkatesh2523** [comment]
https://cloud.r-project.org/bin/linux/ubuntu/

the above URL is of cran package for ubuntu. When we try to add repository as mentioned in the #install R  step. We are getting the issue.
![Screenshot 2024-07-29 192612](https://github.com/user-attachments/assets/7245b819-fa6a-4588-9d78-0674a9887100)

**Comment by eddelbuettel** [comment]
The IP 52.85.151.93 is indeed part of cloudfront.net, a [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) that usually works for everybody (as that is what CDNs do).

If for whatever reason it does not work for you, you *absolutely* can just substitute the principal CRAN host cran.r-project.org or one of its [numerous mirrors sites](https://cran.r-project.org/mirrors.html).  (And note how that page descrive cloud.r-project.org -- I really have not heard of anyone having issue.)

This is still an issue local to you, I think, and between you and CRAN.  r2u can work with any CRAN mirror, so just pick a different one.   Good luck.

(Also: It is generally preferred to document issues in text, not images.)
