### ISSUE TITLE
Step 2 in the README uses the Jammy url instead of Noble

### ISSUE THREAD

**Issue by Constancies** [eddelbuettel/r2u#68]
In Step 2 of the README's install process, this line points to the Jammy repo even though 24.04 is out and supported:

```bash
echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main" \
     > /etc/apt/sources.list.d/cranapt.list
```

This can be solved by changing those lines to this, so that it will automatically detect the Ubuntu version:

```bash
echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu $(lsb_release -cs) main" \
     > /etc/apt/sources.list.d/cranapt.list

**Comment by eddelbuettel** [comment]
I think we need to take the `$(lsb_release -cs)` outside the double quotes.  So

     echo "deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu" $(lsb_release -cs) "main" \
          > /etc/apt/sources.list.d/cranapt.list

is likely better.

**Comment by eddelbuettel** [comment]
We actually say right before step 1:

> We show the setup step by step for 'jammy' aka Ubuntu 22.04.

**Comment by eddelbuettel** [comment]
It also misssed "jammy-cran40" in the step for R binaries.  So I decided to leave the steps at "jammy", but mention `lsb_release -cs` explicitly just before.   So thanks for the note, now addressed.
