### ISSUE TITLE
What website engine do you use?

### ISSUE THREAD

**Issue by jkislin** [eddelbuettel/r2u#71]
Thanks :)

**Comment by jkislin** [comment]
Material for MkDocs. 10-4. Thanks! Great project and great website.

**Comment by eddelbuettel** [comment]
Err, what was the point of this issue? The site, just like the handful of others I did with 'material for mkdocs' clearly state what is used:

![image](https://github.com/user-attachments/assets/434b8b29-8946-435d-a92b-e876817a2a8e)

For what it is worth, I use an older version that I keep fixed via a Docker container.
