### ISSUE TITLE
ORFik bioconductor package seems to be missing

### ISSUE THREAD

**Issue by kforner** [eddelbuettel/r2u#73]
I could not install it. 
So I checked in https://r2u.stat.illinois.edu/ubuntu/pool/dists/ and it's missing for all three versions of ubuntu.
But according to https://www.bioconductor.org/packages/release/bioc/html/ORFik.html it is supposed to be in Bioc 3.20
Did I miss something ?
Thanks

**Comment by eddelbuettel** [comment]
Yes you missed that we clearly document that we do NOT cover all of BioConductor.  From the README.md:

> - all BioConductor packages implied by these plus a 'healthy subset' of the highest [scoring](https://bioconductor.org/packages/stats/bioc/bioc_pkg_scores.tab) BioConductor packages (also covering _e.g._ all BioConductor packages in the Debian and Ubuntu distributions)

That does not say all BioC packages.    

Do you need many others besides ORFik?

**Comment by kforner** [comment]
Ah sorry about that. I read the FAQ but I missed that.

> Do you need many others besides ORFik?
Currently not, and that's not a real problem. 
Just wanted to report in case it was a bug.
But r2u is so great and comfy, that when something goes wrong it's shocking. 

I have implemented it at one of my customer's and the build time went from 1h30 down to a few minutes...

**Comment by eddelbuettel** [comment]
I have added it now.  We already had all its dependents.

**Comment by kforner** [comment]
awesome, thanks
